import React from 'react';

export default function DocumentationPage() {
  return (
    <div style={{ padding: '0 2rem' }}>
      <div style={{ marginBottom: '2rem' }}>
        <h1 className="gradient-text" style={{ fontSize: '2rem', marginBottom: '0.25rem' }}>TrustLayer Documentation</h1>
        <p style={{ color: 'var(--color-text-muted)' }}>Guides, API references, and architectural overviews for the Enterprise AI Governance platform.</p>
      </div>

      <div style={{ display: 'grid', gridTemplateColumns: 'minmax(250px, 1fr) 3fr', gap: '2rem' }}>
        {/* Sidebar Nav */}
        <div className="glass-panel" style={{ padding: '1.5rem', alignSelf: 'start', position: 'sticky', top: '2rem' }}>
          <h3 style={{ fontSize: '1rem', fontWeight: 600, marginBottom: '1rem', color: 'var(--color-text-main)' }}>Contents</h3>
          <ul style={{ listStyle: 'none', padding: 0, margin: 0, display: 'flex', flexDirection: 'column', gap: '0.75rem' }}>
            <li><a href="#getting-started" style={{ color: 'var(--color-primary-emerald)', textDecoration: 'none', fontSize: '0.9rem' }}>Getting Started</a></li>
            <li><a href="#architecture" style={{ color: 'var(--color-text-muted)', textDecoration: 'none', fontSize: '0.9rem' }}>Architecture</a></li>
            <li><a href="#s3-provenance" style={{ color: 'var(--color-text-muted)', textDecoration: 'none', fontSize: '0.9rem' }}>S3 Provenance Engine</a></li>
            <li><a href="#s6-identity" style={{ color: 'var(--color-text-muted)', textDecoration: 'none', fontSize: '0.9rem' }}>S6 Identity & Permissions</a></li>
            <li><a href="#s1-conflict" style={{ color: 'var(--color-text-muted)', textDecoration: 'none', fontSize: '0.9rem' }}>S1 Conflict Arbiter</a></li>
            <li><a href="#s7-hitl" style={{ color: 'var(--color-text-muted)', textDecoration: 'none', fontSize: '0.9rem' }}>S7 HITL Routing</a></li>
          </ul>
        </div>

        {/* Main Doc Content */}
        <div className="glass-panel" style={{ padding: '2rem' }}>
          
          <section id="getting-started" style={{ marginBottom: '3rem' }}>
            <h2 style={{ fontSize: '1.5rem', fontWeight: 600, marginBottom: '1rem', color: 'var(--color-text-main)' }}>Getting Started</h2>
            <p style={{ color: 'var(--color-text-muted)', lineHeight: '1.6', marginBottom: '1rem' }}>
              TrustLayer provides an immutable, cryptographically verifiable ledger for autonomous AI agent fleets. 
              By integrating the TrustLayer SDK, you gain zero-trust observability into all inputs, outputs, and internal semantic intents generated by your agents.
            </p>
            <div style={{ background: 'rgba(0,0,0,0.3)', padding: '1rem', borderRadius: '4px', fontFamily: 'monospace', color: 'var(--color-info-cyan)', fontSize: '0.85rem' }}>
              npm install @trustlayer/sdk
            </div>
          </section>

          <section id="architecture" style={{ marginBottom: '3rem' }}>
            <h2 style={{ fontSize: '1.5rem', fontWeight: 600, marginBottom: '1rem', color: 'var(--color-text-main)' }}>Platform Architecture</h2>
            <p style={{ color: 'var(--color-text-muted)', lineHeight: '1.6', marginBottom: '1rem' }}>
              The platform is composed of 5 loosely-coupled modules running on top of a Supabase Postgres foundation with Ed25519 payload signatures.
            </p>
            <ul style={{ color: 'var(--color-text-muted)', lineHeight: '1.6', paddingLeft: '1.5rem' }}>
              <li style={{ marginBottom: '0.5rem' }}><strong>Edge Functions:</strong> Intercept and hash all external MCP (Model Context Protocol) tool calls.</li>
              <li style={{ marginBottom: '0.5rem' }}><strong>Vector DB:</strong> Stores semantic embeddings for intent overlap detection.</li>
              <li style={{ marginBottom: '0.5rem' }}><strong>Audit Ledger:</strong> Append-only table enforced via Row Level Security (RLS).</li>
            </ul>
          </section>

          <section id="s3-provenance" style={{ marginBottom: '3rem' }}>
            <h2 style={{ fontSize: '1.5rem', fontWeight: 600, marginBottom: '1rem', color: 'var(--color-text-main)' }}>S3 Provenance Engine</h2>
            <p style={{ color: 'var(--color-text-muted)', lineHeight: '1.6' }}>
              Every token generated by an agent is hashed alongside its input prompt and active context window. This creates a cryptographically secure <code>Certificate of Provenance</code> that can be verified externally to prove an AI generated a specific payload without human tampering.
            </p>
          </section>

        </div>
      </div>
    </div>
  );
}
