import { NextRequest, NextResponse } from 'next/server';
import { createAdminClient } from '@/lib/db/supabase';
import { AuditLedgerService } from '@lib/ledger/service';
import { jsPDF } from 'jspdf';
import crypto from 'crypto';

/**
 * Resolve tenant ID from (in order):
 *  1. API key in Authorization header
 *  2. X-Tenant-Id header
 */
async function resolveTenantId(req: NextRequest): Promise<string | null> {
  const apiKey = req.headers.get('authorization')?.replace('Bearer ', '') || '';
  if (apiKey) {
    const supabase = createAdminClient();
    const keyHash = crypto.createHash('sha256').update(apiKey).digest('hex');
    const { data: keyData } = await supabase
      .from('api_keys')
      .select('tenant_id')
      .eq('key_hash', keyHash)
      .single()
      .catch(() => ({ data: null }));

    if (keyData?.tenant_id) return keyData.tenant_id;
  }

  const headerTenantId = req.headers.get('x-tenant-id');
  if (headerTenantId) return headerTenantId;

  return null;
}

/* ─── PDF builder helpers ────────────────────────────────────────────── */

const COLORS = {
  accent: [76, 216, 160] as [number, number, number],
  text: [238, 240, 243] as [number, number, number],
  muted: [154, 160, 172] as [number, number, number],
  bg: [15, 16, 19] as [number, number, number],
  surface: [26, 29, 37] as [number, number, number],
  success: [52, 211, 153] as [number, number, number],
  warning: [251, 191, 36] as [number, number, number],
  danger: [248, 113, 113] as [number, number, number],
};

function statusColor(status: string): [number, number, number] {
  if (status === 'covered') return COLORS.success;
  if (status === 'partial') return COLORS.warning;
  return COLORS.danger;
}

function addCoverPage(doc: jsPDF, opts: {
  regulation: string;
  reportId: string;
  tenantId: string;
  periodStart: string;
  periodEnd: string;
  coverageScore: number;
  generatedAt: string;
}) {
  const w = doc.internal.pageSize.getWidth();
  const h = doc.internal.pageSize.getHeight();

  // Background
  doc.setFillColor(...COLORS.bg);
  doc.rect(0, 0, w, h, 'F');

  // Accent stripe
  doc.setFillColor(...COLORS.accent);
  doc.rect(0, 0, 4, h, 'F');

  // Logo text
  doc.setFontSize(28);
  doc.setTextColor(...COLORS.accent);
  doc.text('RuneSignal', 30, 60);

  // Subtitle
  doc.setFontSize(10);
  doc.setTextColor(...COLORS.muted);
  doc.text('AI Governance & Compliance Platform', 30, 70);

  // Regulation title
  doc.setFontSize(22);
  doc.setTextColor(...COLORS.text);
  const regTitle = opts.regulation === 'eu_ai_act'
    ? 'EU AI Act Compliance Evidence Report'
    : 'ISO 42001 Compliance Evidence Report';
  doc.text(regTitle, 30, 110);

  // Divider
  doc.setDrawColor(...COLORS.accent);
  doc.setLineWidth(0.5);
  doc.line(30, 118, 180, 118);

  // Metadata
  doc.setFontSize(10);
  doc.setTextColor(...COLORS.muted);
  let y = 135;
  const meta = [
    ['Report ID', opts.reportId],
    ['Tenant', opts.tenantId],
    ['Evidence Period', `${opts.periodStart} \u2192 ${opts.periodEnd}`],
    ['Generated', opts.generatedAt],
  ];
  for (const [label, value] of meta) {
    doc.setTextColor(...COLORS.muted);
    doc.text(`${label}:`, 30, y);
    doc.setTextColor(...COLORS.text);
    doc.text(value, 80, y);
    y += 8;
  }

  // Coverage score
  y += 10;
  doc.setFontSize(12);
  doc.setTextColor(...COLORS.muted);
  doc.text('Overall Coverage Score', 30, y);
  y += 12;
  const scoreColor = opts.coverageScore > 80 ? COLORS.success
    : opts.coverageScore > 50 ? COLORS.warning
    : COLORS.danger;
  doc.setFontSize(48);
  doc.setTextColor(...scoreColor);
  doc.text(`${opts.coverageScore}%`, 30, y);

  // Footer
  doc.setFontSize(8);
  doc.setTextColor(...COLORS.muted);
  doc.text(
    'This document was generated by RuneSignal Compliance Engine. It constitutes a good-faith evidence package.',
    30, h - 20,
  );
  doc.text(
    'Legal review by qualified counsel is recommended before submission to regulators.',
    30, h - 14,
  );
}

function addTableOfContents(doc: jsPDF, regulation: string) {
  doc.addPage();
  const w = doc.internal.pageSize.getWidth();
  const h = doc.internal.pageSize.getHeight();
  doc.setFillColor(...COLORS.bg);
  doc.rect(0, 0, w, h, 'F');

  doc.setFontSize(16);
  doc.setTextColor(...COLORS.accent);
  doc.text('Table of Contents', 20, 30);

  doc.setDrawColor(...COLORS.accent);
  doc.setLineWidth(0.3);
  doc.line(20, 35, 100, 35);

  doc.setFontSize(11);
  doc.setTextColor(...COLORS.text);
  let y = 50;
  const items = [
    '1. Cover Page',
    '2. Table of Contents',
    regulation === 'eu_ai_act'
      ? '3. Article Coverage Breakdown'
      : '3. Clause Coverage Breakdown',
    '4. Evidence Summary',
    '5. Attestation & Signature',
  ];
  for (const item of items) {
    doc.text(item, 25, y);
    y += 10;
  }
}

function addEuAiActBreakdown(doc: jsPDF, report: any) {
  doc.addPage();
  const w = doc.internal.pageSize.getWidth();
  const h = doc.internal.pageSize.getHeight();
  doc.setFillColor(...COLORS.bg);
  doc.rect(0, 0, w, h, 'F');

  doc.setFontSize(16);
  doc.setTextColor(...COLORS.accent);
  doc.text('Article Coverage Breakdown', 20, 30);
  doc.setDrawColor(...COLORS.accent);
  doc.setLineWidth(0.3);
  doc.line(20, 35, 130, 35);

  const articles = report?.article_coverage || {};
  const rows: Array<{ ref: string; title: string; status: string; detail: string }> = [
    {
      ref: 'Art. 13',
      title: 'Transparency',
      status: articles.article_13_transparency?.status || 'not_covered',
      detail: `${articles.article_13_transparency?.evidence_count || 0} signed events`,
    },
    {
      ref: 'Art. 14',
      title: 'Human Oversight',
      status: articles.article_14_human_oversight?.status || 'not_covered',
      detail: `${articles.article_14_human_oversight?.hitl_reviews || 0} HITL reviews`,
    },
    {
      ref: 'Art. 17',
      title: 'Quality Management',
      status: articles.article_17_quality_management?.status || 'not_covered',
      detail: `${articles.article_17_quality_management?.anomalies_detected || 0} anomalies tracked`,
    },
    {
      ref: 'Art. 26',
      title: 'Deployer Obligations',
      status: articles.article_26_deployer_obligations?.status || 'not_covered',
      detail: `${articles.article_26_deployer_obligations?.agent_inventory_count || 0} agents inventoried`,
    },
  ];

  let y = 50;

  // Table header
  doc.setFillColor(...COLORS.surface);
  doc.rect(20, y - 5, w - 40, 10, 'F');
  doc.setFontSize(9);
  doc.setTextColor(...COLORS.muted);
  doc.text('Article', 25, y + 2);
  doc.text('Requirement', 55, y + 2);
  doc.text('Status', 110, y + 2);
  doc.text('Evidence', 145, y + 2);
  y += 14;

  for (const row of rows) {
    doc.setFontSize(10);
    doc.setTextColor(...COLORS.text);
    doc.text(row.ref, 25, y);
    doc.text(row.title, 55, y);

    doc.setTextColor(...statusColor(row.status));
    doc.text(row.status.replace('_', ' '), 110, y);

    doc.setTextColor(...COLORS.muted);
    doc.setFontSize(9);
    doc.text(row.detail, 145, y);
    y += 10;
  }

  // Ledger summary
  const ledger = report?.action_ledger_summary || {};
  y += 15;
  doc.setFontSize(14);
  doc.setTextColor(...COLORS.accent);
  doc.text('Action Ledger Summary', 20, y);
  y += 12;

  doc.setFontSize(10);
  const ledgerRows = [
    ['Total Agent Actions', String(ledger.total_actions || 0)],
    ['Cryptographically Signed', String(ledger.cryptographically_signed || 0)],
    ['Coverage', `${ledger.coverage_percentage || 0}%`],
  ];
  for (const [label, value] of ledgerRows) {
    doc.setTextColor(...COLORS.muted);
    doc.text(label, 25, y);
    doc.setTextColor(...COLORS.text);
    doc.text(value, 110, y);
    y += 8;
  }
}

function addIso42001Breakdown(doc: jsPDF, report: any) {
  doc.addPage();
  const w = doc.internal.pageSize.getWidth();
  const h = doc.internal.pageSize.getHeight();
  doc.setFillColor(...COLORS.bg);
  doc.rect(0, 0, w, h, 'F');

  doc.setFontSize(16);
  doc.setTextColor(...COLORS.accent);
  doc.text('Clause Coverage Breakdown', 20, 30);
  doc.setDrawColor(...COLORS.accent);
  doc.setLineWidth(0.3);
  doc.line(20, 35, 130, 35);

  const cc = report?.clause_coverage || {};
  const rows: Array<{ ref: string; title: string; status: string; detail: string }> = [
    {
      ref: '6.1',
      title: 'Risk Management',
      status: cc.risk_management?.status || 'not_covered',
      detail: `${cc.risk_management?.evidence_count || 0} items`,
    },
    {
      ref: '8.2',
      title: 'Technical Documentation',
      status: cc.technical_documentation?.status || 'not_covered',
      detail: `${cc.technical_documentation?.evidence_count || 0} items`,
    },
    {
      ref: '8.5',
      title: 'Human Oversight Logs',
      status: cc.human_oversight_logs?.status || 'not_covered',
      detail: `${cc.human_oversight_logs?.evidence_count || 0} items`,
    },
    {
      ref: '9.1',
      title: 'Accuracy & Robustness',
      status: cc.accuracy_and_robustness?.status || 'not_covered',
      detail: `${cc.accuracy_and_robustness?.evidence_count || 0} items`,
    },
    {
      ref: '10.2',
      title: 'Incident Documentation',
      status: cc.incident_documentation?.status || 'not_covered',
      detail: `${cc.incident_documentation?.evidence_count || 0} items`,
    },
  ];

  let y = 50;

  doc.setFillColor(...COLORS.surface);
  doc.rect(20, y - 5, w - 40, 10, 'F');
  doc.setFontSize(9);
  doc.setTextColor(...COLORS.muted);
  doc.text('Clause', 25, y + 2);
  doc.text('Requirement', 55, y + 2);
  doc.text('Status', 110, y + 2);
  doc.text('Evidence', 145, y + 2);
  y += 14;

  for (const row of rows) {
    doc.setFontSize(10);
    doc.setTextColor(...COLORS.text);
    doc.text(row.ref, 25, y);
    doc.text(row.title, 55, y);

    doc.setTextColor(...statusColor(row.status));
    doc.text(row.status.replace('_', ' '), 110, y);

    doc.setTextColor(...COLORS.muted);
    doc.setFontSize(9);
    doc.text(row.detail, 145, y);
    y += 10;
  }
}

function addAttestationPage(doc: jsPDF, report: any, reportId: string) {
  doc.addPage();
  const w = doc.internal.pageSize.getWidth();
  const h = doc.internal.pageSize.getHeight();
  doc.setFillColor(...COLORS.bg);
  doc.rect(0, 0, w, h, 'F');

  doc.setFontSize(16);
  doc.setTextColor(...COLORS.accent);
  doc.text('Attestation & Signature', 20, 30);
  doc.setDrawColor(...COLORS.accent);
  doc.setLineWidth(0.3);
  doc.line(20, 35, 120, 35);

  let y = 50;
  doc.setFontSize(10);
  const attestation = report?.attestation || {};
  const meta = report?.report_metadata || {};

  const fields = [
    ['Signed By', attestation.signed_by || 'RuneSignal Compliance Engine'],
    ['Timestamp', attestation.timestamp || new Date().toISOString()],
    ['Report ID', reportId],
  ];

  for (const [label, value] of fields) {
    doc.setTextColor(...COLORS.muted);
    doc.text(`${label}:`, 25, y);
    doc.setTextColor(...COLORS.text);
    doc.text(value, 70, y);
    y += 8;
  }

  // Signature (truncated for display)
  y += 5;
  doc.setTextColor(...COLORS.muted);
  doc.text('Signature:', 25, y);
  y += 8;
  doc.setFontSize(7);
  doc.setTextColor(...COLORS.text);
  const sig = attestation.signature || 'N/A';
  // Wrap long signature lines
  const sigLines = doc.splitTextToSize(sig, w - 50);
  doc.text(sigLines, 25, y);
  y += sigLines.length * 4 + 10;

  // Ledger root hash
  if (meta.cryptographic_integrity?.ledger_root_hash) {
    doc.setFontSize(10);
    doc.setTextColor(...COLORS.muted);
    doc.text('Ledger Root Hash:', 25, y);
    y += 8;
    doc.setFontSize(7);
    doc.setTextColor(...COLORS.text);
    const hashLines = doc.splitTextToSize(meta.cryptographic_integrity.ledger_root_hash, w - 50);
    doc.text(hashLines, 25, y);
    y += hashLines.length * 4 + 10;
  }

  // Verification note
  y += 10;
  doc.setFontSize(9);
  doc.setTextColor(...COLORS.muted);
  doc.text('Verification URL:', 25, y);
  doc.setTextColor(...COLORS.accent);
  doc.text(`https://app.runesignal.com/verify/${reportId}`, 70, y);

  // Disclaimer
  y = h - 40;
  doc.setFontSize(8);
  doc.setTextColor(...COLORS.muted);
  const disclaimer = doc.splitTextToSize(
    'This document was generated by RuneSignal Compliance Engine. It constitutes a good-faith evidence package for regulatory compliance purposes. Legal review by qualified counsel is recommended before submission to regulators.',
    w - 40,
  );
  doc.text(disclaimer, 20, y);
}

/* ─── Route handler ──────────────────────────────────────────────────── */

export async function GET(
  req: NextRequest,
  { params }: { params: Promise<{ report_id: string }> }
) {
  try {
    const tenantId = await resolveTenantId(req);
    if (!tenantId) {
      return NextResponse.json({ error: 'Tenant context required' }, { status: 401 });
    }

    const { report_id } = await params;
    const supabase = createAdminClient();

    const { data, error } = await supabase
      .from('compliance_reports')
      .select('status, json_export, pdf_url, regulation, coverage_score, evidence_period_start, evidence_period_end, generated_at, org_id')
      .eq('id', report_id)
      .eq('org_id', tenantId)
      .single();

    if (error || !data) {
      return NextResponse.json({ error: 'Report not found' }, { status: 404 });
    }

    if (data.status !== 'ready') {
      return NextResponse.json({ error: `Report status is ${data.status}` }, { status: 400 });
    }

    // Generate real PDF
    const report = data.json_export as any;
    const regulation = (data.regulation || 'eu_ai_act') as string;
    const coverageScore = data.coverage_score ?? 0;

    const doc = new jsPDF({ orientation: 'portrait', unit: 'mm', format: 'a4' });

    // Cover page
    addCoverPage(doc, {
      regulation,
      reportId: report_id,
      tenantId,
      periodStart: data.evidence_period_start || '',
      periodEnd: data.evidence_period_end || '',
      coverageScore,
      generatedAt: data.generated_at || new Date().toISOString(),
    });

    // Table of contents
    addTableOfContents(doc, regulation);

    // Regulation-specific breakdown
    if (regulation === 'iso_42001') {
      addIso42001Breakdown(doc, report);
    } else {
      addEuAiActBreakdown(doc, report);
    }

    // Attestation page
    addAttestationPage(doc, report, report_id);

    const pdfBuffer = Buffer.from(doc.output('arraybuffer'));

    // Fire-and-forget audit logging for PDF export
    AuditLedgerService.appendEvent({
      event_type: 'evidence.exported.pdf',
      module: 's13',
      tenant_id: tenantId,
      payload: { report_id },
    }).catch(() => {});

    const regLabel = regulation === 'iso_42001' ? 'iso-42001' : 'eu-ai-act';
    return new NextResponse(pdfBuffer, {
      headers: {
        'Content-Type': 'application/pdf',
        'Content-Disposition': `attachment; filename="${regLabel}-report-${report_id}.pdf"`,
      },
    });
  } catch (err) {
    console.error('[compliance/reports/pdf] error:', err);
    return NextResponse.json({ error: 'Internal server error' }, { status: 500 });
  }
}
